import { svgIcon } from "./svgIcon";

import * as AlertSvg from "./alert.svg";
import * as AngleDownSvg from "./angle-down.svg";
import * as AngleUpSvg from "./angle-up.svg";
import * as ArrowDownSvg from "./arrow-down.svg";
import * as ArrowRightSvg from "./arrow-right.svg";
import * as ArrowUpSvg from "./arrow-up.svg";
import * as AudioSvg from "./audio.svg";
import * as BoltSvg from "./bolt.svg";
import * as BoxCubeSvg from "./box-cube.svg";
import * as BoxLineSvg from "./box-line.svg";
import * as BoxSvg from "./box.svg";
import * as CalenderLineSvg from "./calender-line.svg";
import * as ChatSvg from "./chat.svg";
import * as CheckCircleSvg from "./check-circle.svg";
import * as CheckLineSvg from "./check-line.svg";
import * as ChevronDownSvg from "./chevron-down.svg";
import * as ChevronLeftSvg from "./chevron-left.svg";
import * as ChevronUpSvg from "./chevron-up.svg";
import * as CloseLineSvg from "./close-line.svg";
import * as CloseSvg from "./close.svg";
import * as CopySvg from "./copy.svg";
import * as DocsSvg from "./docs.svg";
import * as DollarLineSvg from "./dollar-line.svg";
import * as DownloadSvg from "./download.svg";
import * as EnvelopeSvg from "./envelope.svg";
import * as EyeCloseSvg from "./eye-close.svg";
import * as EyeSvg from "./eye.svg";
import * as FileSvg from "./file.svg";
import * as FlagDeSvg from "./flag-de.svg";
import * as FlagEsSvg from "./flag-es.svg";
import * as FlagSaSvg from "./flag-sa.svg";
import * as FlagUsSvg from "./flag-us.svg";
import * as FolderSvg from "./folder.svg";
import * as GridSvg from "./grid.svg";
import * as GroupSvg from "./group.svg";
import * as HorizontalDotsSvg from "./horizontal-dots.svg";
import * as InfoHexaSvg from "./info-hexa.svg";
import * as InfoSvg from "./info.svg";
import * as ListSvg from "./list.svg";
import * as LockSvg from "./lock.svg";
import * as MailLineSvg from "./mail-line.svg";
import * as MoreDotSvg from "./more-dot.svg";
import * as PageSvg from "./page.svg";
import * as PaperPlaneSvg from "./paper-plane.svg";
import * as PencilSvg from "./pencil.svg";
import * as PieChartSvg from "./pie-chart.svg";
import * as PlugInSvg from "./plug-in.svg";
import * as PlusSvg from "./plus.svg";
import * as ShootingStarSvg from "./shooting-star.svg";
import * as TableSvg from "./table.svg";
import * as TaskIconSvg from "./task-icon.svg";
import * as TimeSvg from "./time.svg";
import * as TrashSvg from "./trash.svg";
import * as UploadSvg from "./upload.svg";
import * as UserCircleSvg from "./user-circle.svg";
import * as UserLineSvg from "./user-line.svg";
import * as VideosSvg from "./videos.svg";

export const AlertIcon = svgIcon(AlertSvg);
export const AngleDownIcon = svgIcon(AngleDownSvg);
export const AngleUpIcon = svgIcon(AngleUpSvg);
export const ArrowDownIcon = svgIcon(ArrowDownSvg);
export const ArrowRightIcon = svgIcon(ArrowRightSvg);
export const ArrowUpIcon = svgIcon(ArrowUpSvg);
export const AudioIcon = svgIcon(AudioSvg);
export const BoltIcon = svgIcon(BoltSvg);
export const BoxCubeIcon = svgIcon(BoxCubeSvg);
export const BoxIconLine = svgIcon(BoxLineSvg);
export const BoxIcon = svgIcon(BoxSvg);
export const BoxTapped = BoxIcon;
export const CalenderIcon = svgIcon(CalenderLineSvg);
export const ChatIcon = svgIcon(ChatSvg);
export const CheckCircleIcon = svgIcon(CheckCircleSvg);
export const CheckLineIcon = svgIcon(CheckLineSvg);
export const ChevronDownIcon = svgIcon(ChevronDownSvg);
export const ChevronLeftIcon = svgIcon(ChevronLeftSvg);
export const ChevronUpIcon = svgIcon(ChevronUpSvg);
export const CloseLineIcon = svgIcon(CloseLineSvg);
export const CloseIcon = svgIcon(CloseSvg);
export const CopyIcon = svgIcon(CopySvg);
export const DocsIcon = svgIcon(DocsSvg);
export const DollarLineIcon = svgIcon(DollarLineSvg);
export const DownloadIcon = svgIcon(DownloadSvg);
export const EnvelopeIcon = svgIcon(EnvelopeSvg);
export const EyeCloseIcon = svgIcon(EyeCloseSvg);
export const EyeIcon = svgIcon(EyeSvg);
export const FileIcon = svgIcon(FileSvg);
export const DeFlagIcon = svgIcon(FlagDeSvg);
export const EsFlagIcon = svgIcon(FlagEsSvg);
export const SaFlagIcon = svgIcon(FlagSaSvg);
export const UsFlagIcon = svgIcon(FlagUsSvg);
export const FolderIcon = svgIcon(FolderSvg);
export const GridIcon = svgIcon(GridSvg);
export const GroupIcon = svgIcon(GroupSvg);
export const HorizontaLDots = svgIcon(HorizontalDotsSvg);
export const ErrorIcon = svgIcon(InfoHexaSvg);
export const InfoIcon = svgIcon(InfoSvg);
export const ListIcon = svgIcon(ListSvg);
export const LockIcon = svgIcon(LockSvg);
export const MailIcon = svgIcon(MailLineSvg);
export const MoreDotIcon = svgIcon(MoreDotSvg);
export const PageIcon = svgIcon(PageSvg);
export const PaperPlaneIcon = svgIcon(PaperPlaneSvg);
export const PencilIcon = svgIcon(PencilSvg);
export const PieChartIcon = svgIcon(PieChartSvg);
export const PlugInIcon = svgIcon(PlugInSvg);
export const PlusIcon = svgIcon(PlusSvg);
export const ShootingStarIcon = svgIcon(ShootingStarSvg);
export const TableIcon = svgIcon(TableSvg);
export const TaskIcon = svgIcon(TaskIconSvg);
export const TimeIcon = svgIcon(TimeSvg);
export const TrashBinIcon = svgIcon(TrashSvg);
export const UploadIcon = svgIcon(UploadSvg);
export const UserCircleIcon = svgIcon(UserCircleSvg);
export const UserIcon = svgIcon(UserLineSvg);
export const VideoIcon = svgIcon(VideosSvg);
